### ISSUE TITLE
Neale is still winning

### ISSUE THREAD

**Issue by davefreyyo** [amaclay/GoTdeathPool#3]
Plz fix

**Comment by amaclay** [comment]
Thank you for your submission. This issue appears to be an unfortunate reality, however I will continue to investigate.

**Comment by amaclay** [comment]
Upon further investigation it appears that the issue lies in the [week4 key file](https://github.com/amaclay/GoTdeathPool/blob/master/data/GoTdeathPool_key_week4.csv). Please contact [HBO](general@hbo.com) to provide feedback about HBO programming.
